version: "3.3"

services:
  gcesdb:
    image: postgres
    container_name: dbgces
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - "dbgcesdata:/var/lib/postgresql/data"
  gcesapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - dbgces
  webserver:
    image: nginx
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gcesapi

volumes:
  dbgcesdata:

networks:
  default:
    name: thiagogmf-gces
